---
title: "Abundance exploration"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
suppressPackageStartupMessages(library(tidyverse))
library(vegan)
library(compositions)
library(ggdendro) 
library(randomForest)
```


```{r readData}
meta <- left_join(k, read_tsv("data/meta.tsv") %>% select(sample_id = SAMPLE_ID, year = Year, geocluster = Geocluster, lat = Latitude, lon = Longitude))
meta$geocluster <- factor(meta$geocluster, levels = c("WEL", "BOR", "TAM", "VER"))
bracken <- read_tsv("data/bracken_report.tsv.gz", col_types = "cnccnn") %>% filter(name != "Homo sapiens")
bracken <- left_join(meta, bracken)

ggplot(meta, aes(year, 1-K, color = geocluster )) + geom_jitter() + stat_smooth(method = "lm", se = F) + ylab("K (fraction African)")
with(meta, cor.test(K, year))


meta %>% filter(geocluster != "VER") %>% ggplot(aes(as.factor(year), 1-K, color = geocluster )) + geom_boxplot() + stat_smooth(method = "lm", se = F) + ylab("K (fraction African)") + facet_grid(geocluster~.) + theme_minimal() + guides(color = F)
```

K is negatively correlated with year, i.e., it is the proportion of European genes in a bee

## Braken
```{r}
ggplot(bracken, aes(log10(fraction_total_reads))) +geom_histogram(bins = 100) + geom_vline(xintercept = log10(10^-4))

brackenFiltered <- filter(bracken, fraction_total_reads > 10^-4) %>% group_by(name) %>% filter(n() > 100) %>% dplyr::select(name, sample_id, year, K, geocluster, fraction_total_reads) %>% pivot_wider(names_from = name, values_from = fraction_total_reads, values_fill = c(fraction_total_reads = 0))

brackenFilteredClr <- clr(brackenFiltered %>% dplyr::select(-K, -year, -sample_id, -geocluster ))
rownames(brackenFilteredClr) <- brackenFiltered$sample_id

dd.row <- as.dendrogram(hclust(dist(t(brackenFilteredClr))))
ddata_x <- dendro_data(dd.row)
labs <- left_join(label(ddata_x), dd)

ggplot(segment(ddata_x)) + geom_segment(aes(x=x, y=y, xend=xend, yend=yend)) +
  geom_text(data=label(ddata_x),aes(label=label, x=x, y=0, colour=labs$group))
ggdendrogram(, color = log(colSums(brackenFiltered %>% dplyr::select(-K, -year, -sample_id, -geocluster ))))

ggsave("dendrogram.pdf", width=14, height = 7)

brackenFilteredPCA <- prcomp(as.data.frame(clr(brackenFiltered %>% dplyr::select(-K, -year, -sample_id, -geocluster ))))
ggbiplot(brackenFilteredPCA, groups = ifelse(brackenFiltered$K<.5, "yes", "no"))

plot(brackenFilteredPCA <- prcomp(as.data.frame(clr(brackenFiltered %>% dplyr::select(-K, -year, -sample_id, -geocluster ))))(dist(clr(brackenFiltered %>% dplyr::select(-K, -year, -sample_id, -geocluster )))))

tibble(x = brackenFilteredPCA$scores[,1], y = brackenFilteredPCA$scores[,2], K = brackenFiltered$K, year = brackenFiltered$year) %>% ggplot(aes(x, y, color = K)) + geom_point()

brackenFilteredMDS <- isoMDS(dist(ilr(brackenFiltered %>% dplyr::select(-K, -year, -sample_id, -geocluster ))), k = 2)

tibble(x =brackenFilteredMDS$points[,1], y =brackenFilteredMDS$points[,2], K = brackenFiltered$K, year = brackenFiltered$year) %>% ggplot(aes(x, y, color = year)) + geom_point()
adonis2(dist(clr(brackenFiltered %>% dplyr::select(-K, -year, -sample_id, -geocluster ) )) ~ K * year, data = brackenFiltered) 
```

t

```{r}
library(psych)
Kcorr <- corr.test(y = brackenFiltered$K, x = as.matrix(brackenFiltered %>% dplyr::select(-year, -sample_id, -geocluster)), method = "spearman", adjust = "fdr")
table(Kcorr$p < 0.05)
hist(Kcorr$r)
data.frame(r= Kcorr$r, p = Kcorr$p) %>% ggplot(aes(r, fill = p<0.05)) + geom_histogram() + xlab("taxa correlated with more African bees")
```
Kcorr$r
